# Generated by Django 2.2 on 2020-08-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryGenesis_app', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
